name: Deploy Routine API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o "PreferredAuthentications=password" -o "PubkeyAuthentication=no" -p 20022 -tt ballbot@121.136.136.157 << 'EOF'
          pm2 stop routine-api || true
          pm2 delete routine-api || true
          cd /home/ballbot/Projects/routine-api
          git pull origin main
          npm ci
          npm run build
          pm2 start dist/main.js --name routine-api
        EOF
