name: Deploy Routine API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: "121.136.136.157"
        username: "ballbot"
        password: ${{ secrets.SSH_PASSWORD }}
        port: 20022
        script: |
          /home/ballbot/.nvm/versions/node/v20.17.0/bin/pm2 stop routine-api || true
          /home/ballbot/.nvm/versions/node/v20.17.0/bin/pm2 delete routine-api || true
          cd /home/ballbot/Projects/routine-api
          git pull origin main
          npm ci
          npm run build
          /home/ballbot/.nvm/versions/node/v20.17.0/bin/pm2 start dist/main.js --name routine-api

